### ISSUE TITLE
Review Request - Labo2

### ISSUE THREAD

**Issue by jbstand** [AMT-TEAM03/AMT-Labo2#20]
@NicolasGlassey 

b230abbec42b5a9530c95e310a85cad9b2296f02

**Comment by NicolasGlassey** [comment]
@jbstand @MasterZeus97 

Bonsoir Messieurs,

J'ai pu exécuter votre .jar sur AWS. Jolie documentation, bon boulot.

Concernant le deuxième paramètre, je ne saisie pas bien. Vous demandez le path de l'image à analyser (ok), mais pourquoi demander un nom d'image à l'utilisateur ?

Quoiqu'il en soit je vous valide ce livrable.

A demain !
