### ISSUE TITLE
Test: AWS Credentials for CI

### ISSUE THREAD

**Issue by jbstand** [AMT-TEAM03/AMT-Labo2#9]
https://github.com/aws-actions/configure-aws-credentials

**Comment by NicolasGlassey** [comment]
/reposted from general teams' channel/
Afin d'utiliser la github action d'AWS pour configurer nos credentials et se connecter, nous avons deux options.
 
La 1ère: Mettre nos credentials dans des variables d'environnement (github secret) qui seront ensuite accessible par notre CI.
La deuxiéme: Utiliser un OIDC token dans notre github environnement et l'utiliser pour assumer notre role IAM. Cette deuxième option est celle recommandée par Amazon.
 
Afin d'utiliser cette seconde option nous avons besoin d'une string représentant notre role IAM. Serait-il possible de l'avoir?

**Comment by jbstand** [comment]
The solution has been implemented using github secrets mapped to the CI environment variables.

#10
